### ISSUE TITLE
Can't install on MacOs Catalina

### ISSUE THREAD

**Issue by voquanghoa** [jwise/HoRNDIS#124]
Hello, 

I have just download the latest version (9.2) but it can't be installed on my Mac. Could you help me to check this.

![image](https://user-images.githubusercontent.com/10450325/89552819-dd3fc900-d836-11ea-9bb5-e1c65b625bd8.png)

Thanks

**Comment by eathtespagheti** [comment]
Same problem here, 10.15.6

**Comment by eathtespagheti** [comment]
Ok apparently there's a workaround, a user fixed the install script and solved the compatibility issues with Catalina, you can find it here  [https://github.com/jwise/HoRNDIS/issues/102#issuecomment-541237232]()

**Comment by voquanghoa** [comment]
It doesn't work on my side, after disabling csrutil from the recovery mode, I restart my mac and try again but I have the same error. You can see in my screenshot, the csrutil is disabled.

 
![image](https://user-images.githubusercontent.com/10450325/89711781-8d880b80-d9b6-11ea-92e3-a2e909818156.png)

**Comment by voquanghoa** [comment]
Try again with file in the comment, it works. Thank you so much. Hopefully, they will release the new one with the changes soon.
