### ISSUE TITLE
Please help how to reinstall hackintosh which requires net so what should I do 

### ISSUE THREAD

**Issue by raj100s** [jwise/HoRNDIS#125]
I have a created a opencore installing pendrive but I don't have ethernet I use usb tethering to use internet on my windows so how should I add this to the opencore pendrive should I add the file and take oc snapshot in config
 please reply

**Comment by eathtespagheti** [comment]
This has nothing to do with HoRNDIS

**Comment by raj100s** [comment]
But it requires net I don't have ethernet so how should I download it is not supporting usb tethering

**Comment by raj100s** [comment]
By reinstall I mean installing hackintosh for first time by reinstall option that i get when I insert my usb containing opensource hackintosh so what changes should I do to this usb drive

**Comment by jwise** [comment]
If you are having trouble installing Mac OS, please contact Apple's support.
