### ISSUE TITLE
Connected but internet connection not working (Big Sur Opencore)

### ISSUE THREAD

**Issue by MuttakinHasib** [jwise/HoRNDIS#134]
**Device: Redmi Note 7**

**Comment by MuttakinHasib** [comment]
![Screen Shot 2020-12-07 at 10 20 35 PM](https://user-images.githubusercontent.com/44552983/101377587-de294b80-3866-11eb-92ba-f8c61d97bfc4.png)

**Comment by MuttakinHasib** [comment]
Problem solved . :)

**Comment by ctaity** [comment]
how do you solved?

**Comment by MuttakinHasib** [comment]
@ctaity 
maybe issue with USB 2.0 port
