### ISSUE TITLE
Share internet from Mac to Android

### ISSUE THREAD

**Issue by makakaorg** [jwise/HoRNDIS#144]
I wanted to know is there opportunity to share internet from Mac (Ethernet-connection) to Android by USB?
I use this option for iPhone with native macOS feature support, and I want to use it for Android.

P.S. It will be useful for health to avoid more radiation like with Wi-Fi, Bluetooth

**Comment by jwise** [comment]
RF energy in the ISM band at regulatory-approved power levels is not ionizing radiation, and has no known health impacts.
