### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by chris1111** [jwise/HoRNDIS#147]
Deleted

**Comment by jarryyen** [comment]
Thank You @chris1111

**Comment by brucedjones** [comment]
@chris1111 I am having the same issue as noted here: https://github.com/chris1111/HoRNDIS/issues/4

I couldn't comment there because your repo is archived. I'm on M1 and need to have SIP enabled, I followed the SIP enabled instructions and had the issue @pradhyumk observed

**Comment by mlostekk** [comment]
@chris1111 Same issue as above.

**Comment by pandres95** [comment]
@chris1111 same issue. Now the repo is not found.

**Comment by aaronkaiyangg** [comment]
thx for 分享

**Comment by aaronkaiyangg** [comment]
邮件已收到，会尽快回复，谢谢！
