### ISSUE TITLE
Project now support Monterey 12 and BigSur 11

### ISSUE THREAD

**Issue by chris1111** [jwise/HoRNDIS#148]
Yes Follow My Repos ☞ [I Have Update the Project for macOS12 and macOS11](https://github.com/chris1111/HoRNDIS)

**Comment by droidguyg1** [comment]
Great, @chris1111! Anyone can confirm that it works with Big Sur?  Which minor versions of Big Sur.

**Comment by bytes-as** [comment]
Hi @droidguyg1 , Can't confirm for Big Sur but I have just installed this in intel based MacBook Pro with macOS Monterey. I did the installation from pre-build release package file from the instructions given there. It all work just fine, all I did was follow the steps. I think it's safe to assume that it will gonna work in Big Sur as well.

Thanks @chris1111, great work.

**Comment by clauderoy790** [comment]
The link is dead, can someone post the new link if it's still available?

**Comment by sanket17096** [comment]
Did you find the workaround?

**Comment by bytes-as** [comment]
Hi, You guys can check out @chris1111 's other repositories, I found this [one](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter). As far as I understand from the readme, it should work.
