### ISSUE TITLE
Enable USB extra current charging on MacBook

### ISSUE THREAD

**Issue by larstobi** [jwise/HoRNDIS#51]
When connecting an Android phone to a Macbook, it will only charge at 500 mA. When connecting an Apple iPhone, it will charge at 900 mA or even 2100 mA on a USB port.

Is it possible to make OS X (Yosemite) provide extra current to a phone when connected using HoRNDIS? That way I can charge the phone much more quickly while tethering with USB.

* https://support.apple.com/en-us/HT204377
* http://forum.xda-developers.com/showthread.php?t=2550896

**Comment by jwise** [comment]
I wish.  Unfortunately, this requires support on the device end, not on the host end.  There is a 'hidden' way for iPhones to get a message saying that they can use extra current: https://github.com/mkorenkov/ipad_charge/wiki

But the device needs to support this, and Android devices don't.
