### ISSUE TITLE
speed slow on mac (.12mbit) vs. 25mbit on phone

### ISSUE THREAD

**Issue by kneegrows** [jwise/HoRNDIS#61]
I'm wondering why I'm having such a huge speed difference in speed, used speed test.net on both devices Galaxy S6 and early 2015 MBP. I was wondering also how I would go about masking the tether from my carrier? maybe clone the MAC of my device?

Thanks in advance
         Knee

**Comment by sparr** [comment]
I also see very slow speeds with USB tethering from a Galaxy S7 to my 2016 MBP, while Wifi tethering is fast as are speeds on the phone itself.

**Comment by mikhailai** [comment]
No response from people involved, closing.
