### ISSUE TITLE
Samsung Galaxy S6 (Edge) [rooted] not recognized on OS X 12.3 with repl8

### ISSUE THREAD

**Issue by gerwin3** [jwise/HoRNDIS#68]
I tried the kextload / unload trick. It does not seem to have an effect. Platform tools are installed. The device does not show in the network settings. Rebooting also does not work. Btw, kextload does not emit any error messages. Any idea what the problem could be?

**Comment by arpitjindal97** [comment]
I am also facing same problem with all of my Samsung devices

**Comment by MrVanosh** [comment]
me too

**Comment by mikhailai** [comment]
Is this issue is still relevant for anyone here? If so, please try the latest HoRNDIS 9.1 release, and see if the issue is still there.

**Comment by mikhailai** [comment]
No reply. Assuming the issue is no loner relevant.
