### ISSUE TITLE
Unable to allow the dev

### ISSUE THREAD

**Issue by rignaneseleo** [jwise/HoRNDIS#81]
Hi,
I'm running High Sierra 10.13.5 and I installed the app but it doesn't work.
It is blocked by the system and I'm not able to unlock it.

If I do: `sudo kextload /Library/Extensions/HoRNDIS.kext`
I receve 

> /Library/Extensions/HoRNDIS.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).

If I go to Privacy settings, it shows me:

> Some system software was blocked from loading. 

There is a button "Allow" but if I push it, it does nothing.

I rebooted many times but no way.

Any solution?

**Comment by mikhailai** [comment]
Hi Leo,
We published a new HoRNDIS 9.1 release. If you still care about the issue, you can try to see if things would work with it.
Also, please make sure the settings Allow apps downloaded from "App Store and identified developers".

**Comment by mikhailai** [comment]
No response from the author. Assuming it's no longer an issue and closing.
