### ISSUE TITLE
Self-assigned IP

### ISSUE THREAD

**Issue by m147** [jwise/HoRNDIS#86]
macOs 10.11.6
HoRNDIS 8

I was having issues with HoRNDIS causing kernel panics. It used to be fine but all of a sudden started to cause kernel panics.  I uninstalled the two kexts as per instructions on the site.  I then installed the latest version 9.0.  When I connect my phone to the macbook and turn on USB tether, it connects but says it has a self-assigned IP.  Any ideas?

**Comment by m147** [comment]
Hi, restarting the phone and MacBook did the trick.  Connected first go, no problem.  Also seems to have fixed the kernel panics, used it as normally for about 45min, no problems. Thanks for the help.

**Comment by mikhailai** [comment]
Glad that worked. Thanks for letting me know.
