### ISSUE TITLE
Won't install in OS X 10.6

### ISSUE THREAD

**Issue by Husky2222** [jwise/HoRNDIS#90]
I have an old MacBook Pro (2008) that I'd love to install this on but I'm getting "the operation couldn't be completed (com.apple.installer.pagecontroller error -1)"

Any workarounds?

**Comment by mikhailai** [comment]
Which HoRNDIS version did you try to install? Note that the latest 9.x versions require OS X 10.11 or later. I would recommend you to try "rel7".

**Comment by Husky2222** [comment]
I installed the 9.1 version and my macOS is 32bit

**Comment by Husky2222** [comment]
Is that my main cause of my error?

**Comment by mikhailai** [comment]
Yes

**Comment by Husky2222** [comment]
I did install it and it works! It installed no problem!

**Comment by Husky2222** [comment]
Issue solved! If you are getting the same error I have install the rel7 version
